display_errors = Off
display_startup_errors = Off

log_errors = On
error_reporting = E_ALL

; ⚠ IMPORTANT: Set the correct path for your server!
error_log = "C:\wamp64\www\projects\showcase\shopcity\storage\logs\php-error.log" 

